# Generated by Django 5.0.7 on 2024-08-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0004_abducteetestimony_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abducteetestimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='abductee_testimonies/'),
        ),
        migrations.AlterField(
            model_name='abducteetestimony',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='abducteetestimony',
            name='date_of_return',
            field=models.DateField(),
        ),
    ]
