# Generated by Django 5.0.7 on 2024-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0006_alter_abducteetestimony_owner_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
