# Generated by Django 5.0.7 on 2024-08-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0007_alter_comment_options_alter_comment_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novapartytestimony',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
