# Generated by Django 5.0.7 on 2024-08-20 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0008_alter_novapartytestimony_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abducteetestimony',
            old_name='image',
            new_name='photo',
        ),
    ]
