# Generated by Django 5.0.7 on 2024-08-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0008_alter_novapartytestimony_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abducteetestimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimony_images/'),
        ),
    ]
