# Generated by Django 5.0.7 on 2024-08-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0009_alter_abducteetestimony_image'),
        ('ironSwordsApp', '0009_rename_image_abducteetestimony_photo'),
    ]

    operations = [
    ]
