# Generated by Django 5.0.7 on 2024-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abducteetestimony',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/'),
        ),
        migrations.AlterField(
            model_name='abducteetestimony',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
