# Generated by Django 5.0.7 on 2024-07-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0002_hero_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='user',
        ),
    ]
