# Generated by Django 5.0.7 on 2024-08-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0002_alter_abducteetestimony_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('date_lit', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
