# Generated by Django 5.0.7 on 2024-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0003_remove_hero_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
