# Generated by Django 5.0.7 on 2024-07-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0006_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
