# Generated by Django 5.0.7 on 2024-07-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0007_alter_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='heroes/'),
        ),
    ]
