# Generated by Django 5.0.7 on 2024-08-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0003_abducteetestimony'),
    ]

    operations = [
        migrations.AddField(
            model_name='abducteetestimony',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abducteetestimony',
            name='date_of_return',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
