# Generated by Django 5.0.7 on 2024-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0010_kibbutzstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='kibbutzstory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
