# Generated by Django 5.0.7 on 2024-08-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0011_kibbutzstory_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaPartyTestimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('story', models.TextField()),
            ],
        ),
    ]
