# Generated by Django 5.0.7 on 2024-08-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ironSwordsApp', '0014_novapartytestimony_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novapartytestimony',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='novapartytestimony',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='novapartytestimony',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
